function [B, T, L] = init_B(u)
    Nv = size(u, 1) / 12;
    B = zeros(3*Nv, 9*Nv);
    u1x = Nv+1: 2*Nv;
    u1y = 2*Nv+1: 3*Nv;
    u2x = 4*Nv+1: 5*Nv;
    u2y = 5*Nv+1: 6*Nv;
    u3x = 7*Nv+1: 8*Nv;
    u3y = 8*Nv+1: 9*Nv;
    uxx = 9*Nv+1: 10*Nv;
    uxy = 10*Nv+1: 11*Nv;
    uyy = 11*Nv+1: 12*Nv;
    B(1: Nv, [u1x, u2x, u3x]) = 2 * [diag(u(u1x)), diag(u(u2x)), diag(u(u3x))];
    B(Nv+1: 2*Nv, [u1x, u2x, u3x, u1y, u2y, u3y]) = [diag(u(u1y)), diag(u(u2y)), diag(u(u3y)), diag(u(u1x)), diag(u(u2x)), diag(u(u3x))];
    B(2*Nv+1: 3*Nv, [u1y, u2y, u3y]) = 2 * [diag(u(u1y)), diag(u(u2y)), diag(u(u3y))];
    B = sparse(B);
    T = [zeros(Nv), zeros(Nv), zeros(Nv); zeros(Nv), 2*diag(uxx), diag(uxy); zeros(Nv), diag(uxy), 2*diag(uyy)];
    T = sparse([T, zeros(3*Nv), zeros(3*Nv); zeros(3*Nv), T, zeros(3*Nv); zeros(3*Nv),zeros(3*Nv), T]);
    L = zeros(12*Nv, 1);
    L(u1x) = 2 * u(uxx) .* u(u1x) + u(uxy) .* u(u1y);
    L(u1y) = u(uxy) .* u(u1x) + 2 * u(uyy) .* u(u1y);
    L(u2x) = 2 * u(uxx) .* u(u2x) + u(uxy) .* u(u2y);
    L(u2y) = u(uxy) .* u(u2x) + 2 * u(uyy) .* u(u2y);
    L(u3x) = 2 * u(uxx) .* u(u3x) + u(uxy) .* u(u3y);
    L(u3y) = u(uxy) .* u(u3x) + 2 * u(uyy) .* u(u3y);
    L(uxx) = u(u1x).^2 + u(u2x).^2 + u(u3x).^2 - 1;
    L(uxy) = u(u1x) .* u(u1y) + u(u2x) .* u(u2y) + u(u3x) .* u(u3y);
    L(uyy) = u(u1y).^2 + u(u2y).^2 + u(u3y).^2 - 1;
end